In [ ]:
from google.colab import files
uploaded = files.upload()

Saving dataset_file.csv.xlsx to dataset_file.csv.xlsx

In [ ]:
!pip install openpyxl

Requirement already satisfied: openpyxl in /usr/local/lib/python3.12/dist-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.12/dist-packages (from openpyxl) (2.0.0)

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
file_name = list(uploaded.keys())[0]

df = pd.read_excel(file_name)

df.head()

,Country,State,Crop,Season,Year,Soil_Type,Soil_pH,Soil_Moisture_%,Nitrogen_N,Phosphorus_P,Potassium_K,Temperature_C,Rainfall_mm,Humidity_%,Wind_Speed_kmph,Irrigation_Type,Area_hectare,Yield_kg_per_ha
0,India,Gujarat,Banana,Rabi,2006,Clay,7.52,28.5,94,19,36,27.6,1119,60,3.7,Rainfed,14.81,45201.8
1,India,Tamil Nadu,Maize,Zaid,2025,Laterite,5.90,39.3,112,59,27,19.8,475,54,3.2,Canal,2.89,3287.6
2,India,Uttar Pradesh,Soybean,Kharif,2015,Red,6.53,59.0,102,74,117,34.2,727,77,4.5,Drip,5.68,1284.9
3,India,Gujarat,Chickpea,Kharif,2006,Loamy,7.77,53.0,74,67,104,28.1,435,80,19.8,Sprinkler,9.98,973.0
4,India,Bihar,Mustard,Kharif,2012,Red,6.96,50.5,76,55,80,39.3,285,81,18.1,Rainfed,11.44,1751.8

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14999 entries, 0 to 14998
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Country          14999 non-null  object
 1   State            14999 non-null  object
 2   Crop             14999 non-null  object
 3   Season           14999 non-null  object
 4   Year             14999 non-null  int64
 5   Soil_Type        14999 non-null  object
 6   Soil_pH          14999 non-null  float64
 7   Soil_Moisture_%  14999 non-null  float64
 8   Nitrogen_N       14999 non-null  int64
 9   Phosphorus_P     14999 non-null  int64
 10  Potassium_K      14999 non-null  int64
 11  Temperature_C    14999 non-null  float64
 12  Rainfall_mm      14999 non-null  int64
 13  Humidity_%       14999 non-null  int64
 14  Wind_Speed_kmph  14999 non-null  float64
 15  Irrigation_Type  14999 non-null  object
 16  Area_hectare     14999 non-null  float64
 17  Yield_kg_per_ha  14999 non-null  float64
dtypes: float64(6), int64(6), object(6)
memory usage: 2.1+ MB

In [ ]:
df.describe()

,Year,Soil_pH,Soil_Moisture_%,Nitrogen_N,Phosphorus_P,Potassium_K,Temperature_C,Rainfall_mm,Humidity_%,Wind_Speed_kmph,Area_hectare,Yield_kg_per_ha
count,14999.000000,14999.000000,14999.000000,14999.000000,14999.000000,14999.000000,14999.000000,14999.000000,14999.000000,14999.000000,14999.000000,14999.000000
mean,2012.532636,6.644098,39.864218,84.314554,44.141076,64.755784,27.438663,1101.615841,62.438763,12.985146,7.745538,11301.870718
std,7.418166,0.665262,11.550669,37.713155,20.106957,31.778026,7.138567,518.831669,18.666080,6.907265,4.181298,17920.144472
min,2000.000000,5.500000,20.000000,20.000000,10.000000,10.000000,15.000000,201.000000,30.000000,1.000000,0.500000,770.200000
25%,2006.000000,6.080000,29.800000,52.000000,27.000000,37.000000,21.300000,645.000000,46.000000,7.000000,4.090000,1524.000000
50%,2012.000000,6.630000,39.900000,84.000000,44.000000,65.000000,27.400000,1108.000000,63.000000,13.100000,7.740000,2314.100000
75%,2019.000000,7.220000,49.800000,117.000000,62.000000,92.000000,33.600000,1546.000000,78.000000,18.900000,11.340000,16955.900000
max,2025.000000,7.800000,60.000000,149.000000,79.000000,119.000000,40.000000,2000.000000,95.000000,25.000000,15.000000,90775.200000

In [ ]:
df.isnull().sum()

Country            0
State              0
Crop               0
Season             0
Year               0
Soil_Type          0
Soil_pH            0
Soil_Moisture_%    0
Nitrogen_N         0
Phosphorus_P       0
Potassium_K        0
Temperature_C      0
Rainfall_mm        0
Humidity_%         0
Wind_Speed_kmph    0
Irrigation_Type    0
Area_hectare       0
Yield_kg_per_ha    0
dtype: int64

In [ ]:
df = df.dropna()

df = df.drop_duplicates()

print("Cleaned Data Shape:", df.shape)

Cleaned Data Shape: (9605, 18)

In [ ]:
X = df.drop(columns=["Yield_kg_per_ha","Area_hectare","Nitrogen_N","Phosphorus_P","Potassium_K"], errors='ignore')

y = df["Yield_kg_per_ha"]

print("Feature shape:", X.shape)
print("Target shape:", y.shape)

Feature shape: (9605, 13)
Target shape: (9605,)

In [ ]:
X = pd.get_dummies(X)

print("New Feature Shape:", X.shape)

New Feature Shape: (9605, 53)

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_temp, y_train, y_temp = train_test_split(
    X, y, test_size=0.3, random_state=42
)

print("Train shape:", X_train.shape)

Train shape: (6723, 53)

In [ ]:
X_val, X_test, y_val, y_test = train_test_split(
    X_temp, y_temp, test_size=0.5, random_state=42
)

print("Validation shape:", X_val.shape)
print("Test shape:", X_test.shape)

Validation shape: (1441, 53)
Test shape: (1441, 53)

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor

In [ ]:
lr = LinearRegression()

lr.fit(X_train, y_train)

y_pred_lr = lr.predict(X_test)

from sklearn.metrics import r2_score, mean_absolute_error

print("Linear Regression Results")

print("R2 Score:", r2_score(y_test, y_pred_lr))

print("MAE:", mean_absolute_error(y_test, y_pred_lr))

Linear Regression Results
R2 Score: 0.9593632161018515
MAE: 1703.902784581053

In [ ]:
dt = DecisionTreeRegressor()

dt.fit(X_train, y_train)

y_pred_dt = dt.predict(X_test)

print("Decision Tree Results")

print("R2 Score:", r2_score(y_test, y_pred_dt))

print("MAE:", mean_absolute_error(y_test, y_pred_dt))

Decision Tree Results
R2 Score: 0.9233852483843431
MAE: 2189.3529493407354

In [ ]:
rf = RandomForestRegressor()

rf.fit(X_train, y_train)

y_pred_rf = rf.predict(X_test)

print("Random Forest Results")

print("R2 Score:", r2_score(y_test, y_pred_rf))

print("MAE:", mean_absolute_error(y_test, y_pred_rf))

Random Forest Results
R2 Score: 0.9566280826257304
MAE: 1721.822903539209